### ISSUE TITLE
Finna-liitännäinen: Lisätään liitännäiselle puuttuva versionumero

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/koha-plugin-rest-di#9]
Liitännäiselle ei ole määritetty versionumeroa ja sen sijaan kannasta löytyy arvo {VERSION}. Tästä ilmeisesti syntyy lokeille virhe 

>Use of uninitialized value $plugin_version in string ne at /home/koha/Koha/Koha/Plugins/Base.pm line 81.

Lisätään versionumero liitännäiseen (ja tarvittaessa käydään ajamassa muutos myös kantaan).

**Comment by emta001** [comment]
Lisätty ja testattu testeillä. Versionumero pysyy nyt nätisti paikallaan tietokannassa. Siitä tuleeko tuota herjaa enää en osaa sanoa, mutta ehkäpä se selviää kun viedään tää tuotantoon.

**Comment by emta001** [comment]
Viety tuotantoon.

**Comment by CodoDerDritte** [comment]
Puuttuvasta versionumerosta tulee edelleen lokimerkintöjä, ainakin apachen lokehin:

```
Mon Dec 09 00:00:01.578654 2024] [core:notice] [pid 305:tid 140675704138816] AH00094: Command line: '/usr/sbin/apache2'
Use of uninitialized value $plugin_version in string ne at /home/koha/Koha/Koha/Plugins/[Base.pm](http://base.pm/) line 81
```

**Comment by emta001** [comment]
> Puuttuvasta versionumerosta tulee edelleen lokimerkintöjä, ainakin apachen lokehin:
> 
> ```
> Mon Dec 09 00:00:01.578654 2024] [core:notice] [pid 305:tid 140675704138816] AH00094: Command line: '/usr/sbin/apache2'
> Use of uninitialized value $plugin_version in string ne at /home/koha/Koha/Koha/Plugins/[Base.pm](http://base.pm/) line 81
> ```

Niin näyttäs tulevan myös plackin lokiin. Pitää varmaan avata ihan oma tikettinsä tälle, kerta tää ei johtunut tästä Finna-plugarista.

**Comment by emta001** [comment]
Äsh, taisin tutkiakin tätä joku hetki sitten ja totesin, että ongelma liittynee globaalien muuttujien käyttämiseen. Meillä on kaikissa plugareissa nyt versionumero paikallaan, mutta miun nähdäkseni sitä versionumeroa ei kutsuta edes kannasta, vaan plugareissa kiinni olevasta muuttujasta _our $metadata_. Samoin siellä on muuttuja _our $VERSION_, jota käytetään tuossa _$metadata_ muuttujassa. Pasi muisteli, että plack estää sen, että funktio ei näe funktion ulkopuolisia muuttujia. Eli tässä voi käydä nyt niin, että kun Base.pm kutsuu plugarin metodia _new_, plack estääkin jommankumman muuttujan kutsumisen. Ja siitä syntyy sitten virhe, kun plugaria syystä tai toisesta yritetään päivittää.

**Comment by emta001** [comment]
Tein uuden tiketin 
[Liitännäiset: Varoitus muuttujan $plugin_value puuttuvasta arvosta täyttää lokit #1556](https://github.com/KohaSuomi/Koha/issues/1556). Suljen tämän.
